### ISSUE TITLE
 'NoneType' object has no attribute 'shape' 问题

### ISSUE THREAD

**Issue by Foxschwarzengel** [panshujia/pcr-farm-script#10]
有没有大佬知道这个错误是什么原因导致的？
Traceback (most recent call last):
  File "Z:/python/first/farm.py", line 199, in <module>
    login(lines[i], [accountList[i + step * 4].split(' ')[0], accountList[i + step * 4].split(' ')[1][0:-1]])
  File "Z:/python/first/farm.py", line 120, in login
    if Image_to_position(image, m=0) != False:
  File "Z:/python/first/farm.py", line 43, in Image_to_position
    template = resize_img(image_path)
  File "Z:/python/first/farm.py", line 33, in resize_img
    height, width = img1.shape[:2]

**Comment by panshujia** [comment]
说明没有那张图片

**Comment by Foxschwarzengel** [comment]
所以大佬那张图一般是放在哪里的，可能是因为地址没有找到

**Comment by panshujia** [comment]
放在images文件夹里面

**Comment by Foxschwarzengel** [comment]
在images里本身存在图片，是不是因为程序某一行images相关的命令没有地址导致程序无法检索到images文件夹里的图导致的？因为之前os.popen的时候我也出现了类似的问题

**Comment by panshujia** [comment]
可能是绝对路径相对路径的问题，我用的是相对路径，可以换成绝对路径试试

**Comment by Foxschwarzengel** [comment]
谢谢大佬我去试试
