### ISSUE TITLE
93行tohomepage显示list out of range

### ISSUE THREAD

**Issue by Foxschwarzengel** [panshujia/pcr-farm-script#9]
大佬我90行的to homepage显示list out of range，所属错误为tohomepage(lines)是什么问题WWW，请教大佬

Traceback (most recent call last):
  File "Z:/python/first/farm.py", line 201, in <module>
    tohomepage(lines)
  File "Z:/python/first/farm.py", line 93, in tohomepage
    screenshot(nameList[0])
IndexError: list index out of range

**Comment by Foxschwarzengel** [comment]
这个问题以及解决了，是adb非os命令，需要输入adb所在的地址加上 adb devices
